Repository mitodl/ol-data-platform, pull requests merged in 2023-08, with the labels that each got.

#791 xpro cms pages
  src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__courses.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__courses_to_topics.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__coursesfaculty.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__coursesinprogram.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__programs.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__programsfaculty.sql
  src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml
  src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_certificatepage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_coursepage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_coursepage_topics.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_coursesinprogrampage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_facultymemberspage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_programpage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__cms_signatorypage.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__wagtail_page.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__wagtail_pagerevision.sql
Labels: needs review

#801 add company and position profile data to int__mitx__users
  src/ol_dbt/models/intermediate/combined/int__combined__users.sql
  src/ol_dbt/models/intermediate/mitx/_int_mitx__models.yml
  src/ol_dbt/models/intermediate/mitx/int__mitx__users.sql
  src/ol_dbt/models/staging/mitxonline/stg__mitxonline__app__postgres__users_userprofile.sql
Labels: needs review

#808 Add openedx_user_id xPro users
  src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__users.sql
  src/ol_dbt/models/intermediate/mitxpro/openedx/_int_openedx_mitxpro__models.yml
  src/ol_dbt/models/intermediate/mitxpro/openedx/int__openedx_mitxpro__users.sql
  src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml
  src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__openedx__mysql__auth_user.sql
Labels: needs review

#810 fix dbt test
  src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
  src/ol_dbt/models/intermediate/salesforce/_int_salesforce__models.yml
  src/ol_dbt/models/staging/salesforce/_stg_salesforce__models.yml
Labels: needs review, waiting on author

#809 Add data freshness tests
  src/ol_dbt/models/staging/mitxonline/_mitxonline__sources.yml
  src/ol_dbt/models/staging/mitxonline/_stg_mitxonline__models.yml
  src/ol_dbt/models/staging/mitxpro/_mitxpro__sources.yml
  src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
  src/ol_dbt/packages.yml
Labels: waiting on author

#814 Fix for issue 1908 to populate parent run id's more consistently
  src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml
  src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productlist.sql
Labels: needs review
