Repository mitodl/ol-data-platform, pull requests merged in 2024-03, with the labels that each got.

#987 add micromasters int and mart tables for exam grades
  src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
  src/ol_dbt/models/intermediate/micromasters/int__micromasters__dedp_proctored_exam_grades.sql
  src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
  src/ol_dbt/models/marts/micromasters/marts__micromasters_dedp_exam_grades.sql
Labels: needs review

#1018 Create staging and intermediate models for bootcamps application related tables
  src/ol_dbt/models/intermediate/bootcamps/_int_bootcamps__models.yml
  src/ol_dbt/models/intermediate/bootcamps/int__bootcamps__applications.sql
  src/ol_dbt/models/staging/bootcamps/_bootcamps__sources.yml
  src/ol_dbt/models/staging/bootcamps/_stg_bootcamps__models.yml
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__applications_applicationstep.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__applications_applicationstep_submission.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__applications_courserun_application.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__applications_courserun_applicationstep.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__courses_installment.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__courses_personalprice.sql
  src/ol_dbt/models/staging/bootcamps/stg__bootcamps__app__postgres__django_contenttype.sql
Labels: needs review

#1021 add income fields to mitxonline users mart
  src/ol_dbt/models/marts/mitxonline/_marts__mitxonline__models.yml
  src/ol_dbt/models/marts/mitxonline/marts__mitxonline_user_profiles.sql
Labels: product:mitx-online, needs review

#984 Process course xml to extract video metadata
  src/ol_orchestrate/lib/openedx.py
Labels: needs review

#1027 updates to edxorg tracking log staging model
  src/ol_dbt/models/staging/edxorg/_edxorg_sources.yml
  src/ol_dbt/models/staging/edxorg/stg__edxorg__s3__tracking_logs__user_activity.sql
Labels: needs review

#935 updates to prod line mart table and the intermediate courses table
  src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__courses.sql
  src/ol_dbt/models/intermediate/mitxpro/int__mitxpro__program_runs.sql
  src/ol_dbt/models/marts/mitxpro/_marts__mitxpro__models.yml
  src/ol_dbt/models/marts/mitxpro/marts__mitxpro_ecommerce_productlist.sql
  src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__courses_course.sql
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__app__postgres__courses_program.sql
Labels: needs review

#1022 create staging and intermediate models for OCW courses
  src/ol_dbt/dbt_project.yml
  src/ol_dbt/macros/transform_code_to_readable_values.sql
  src/ol_dbt/macros/transform_user_profile_values.sql
  src/ol_dbt/models/intermediate/ocw/_int_ocw__models.yml
  src/ol_dbt/models/intermediate/ocw/int__ocw__course_departments.sql
  src/ol_dbt/models/intermediate/ocw/int__ocw__course_instructors.sql
  src/ol_dbt/models/intermediate/ocw/int__ocw__course_topics.sql
  src/ol_dbt/models/intermediate/ocw/int__ocw__courses.sql
  src/ol_dbt/models/staging/ocw/_ocw__sources.yml
  src/ol_dbt/models/staging/ocw/_stg_ocw__models.yml
  src/ol_dbt/models/staging/ocw/stg__ocw__studio__postgres__websites_website.sql
  src/ol_dbt/models/staging/ocw/stg__ocw__studio__postgres__websites_websitecontent.sql
  src/ol_dbt/models/staging/ocw/stg__ocw__studio__postgres__websites_websitestarter.sql
Labels: needs review

#1028 Create OCW course mart
  src/ol_dbt/models/intermediate/ocw/int__ocw__courses.sql
  src/ol_dbt/models/marts/ocw/_marts__ocw__models.yml
  src/ol_dbt/models/marts/ocw/marts__ocw_courses.sql
Labels: needs review

#1040 add primary key to micromasters program certificate models
  src/ol_dbt/macros/generate_hash_id.sql
  src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
  src/ol_dbt/models/intermediate/edxorg/int__edxorg__mitx_program_certificates.sql
  src/ol_dbt/models/intermediate/micromasters/_int_micromasters__models.yml
  src/ol_dbt/models/intermediate/micromasters/int__micromasters__program_certificates.sql
  src/ol_dbt/models/intermediate/micromasters/subqueries/__int_micromasters_subqueries__models.yml
  src/ol_dbt/models/intermediate/micromasters/subqueries/__micromasters_program_certificates_dedp_from_micromasters.sql
  src/ol_dbt/models/intermediate/micromasters/subqueries/__micromasters_program_certificates_dedp_from_mitxonline.sql
  src/ol_dbt/models/intermediate/micromasters/subqueries/__micromasters_program_certificates_non_dedp.sql
  src/ol_dbt/models/marts/micromasters/_marts_micromasters__models.yml
  src/ol_dbt/models/staging/micromasters/_stg_micromasters__models.yml
  src/ol_dbt/models/staging/micromasters/stg__micromasters__app__user_program_certificate_override_list.sql
Labels: needs review

#1041 add grade and course fields to marts
  src/ol_dbt/models/marts/combined/_marts__combined__models.yml
  src/ol_dbt/models/marts/combined/marts__combined_course_enrollment_detail.sql
Labels: needs review

#1042 Apply deduplication to dbt models for airbyte incremental sync using a timestamp cursor field
  src/ol_dbt/macros/apply_deduplication_query.sql
  src/ol_dbt/models/external/irx/mitx/irx__mitx__openedx__mysql__certificates_generatedcertificate.sql
  src/ol_dbt/models/external/irx/mitx/irx__mitx__openedx__mysql__grades_persistentcoursegrade.sql
  src/ol_dbt/models/external/irx/mitx/irx__mitx__openedx__mysql__grades_persistentsubsectiongrade.sql
  src/ol_dbt/models/external/irx/mitx/irx__mitx__openedx__mysql__workflow_assessmentworkflow.sql
  src/ol_dbt/models/external/irx/mitxonline/irx__mitxonline__openedx__mysql__certificates_generatedcertificate.sql
  src/ol_dbt/models/external/irx/mitxonline/irx__mitxonline__openedx__mysql__grades_persistentcoursegrade.sql
  src/ol_dbt/models/external/irx/mitxonline/irx__mitxonline__openedx__mysql__grades_persistentsubsectiongrade.sql
  src/ol_dbt/models/external/irx/mitxonline/irx__mitxonline__openedx__mysql__workflow_assessmentworkflow.sql
  src/ol_dbt/models/external/irx/xpro/irx__xpro__openedx__mysql__certificates_generatedcertificate.sql
  src/ol_dbt/models/external/irx/xpro/irx__xpro__openedx__mysql__grades_persistentcoursegrade.sql
  src/ol_dbt/models/external/irx/xpro/irx__xpro__openedx__mysql__grades_persistentsubsectiongrade.sql
  src/ol_dbt/models/external/irx/xpro/irx__xpro__openedx__mysql__workflow_assessmentworkflow.sql
  src/ol_dbt/models/intermediate/bootcamps/_int_bootcamps__models.yml
  src/ol_dbt/models/intermediate/mitxpro/_int_mitxpro__models.yml
  src/ol_dbt/models/staging/bootcamps/_stg_bootcamps__models.yml
  src/ol_dbt/models/staging/mitxonline/_stg_mitxonline__models.yml
  src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__courseware_studentmodule.sql
  src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__grades_subsectiongrade.sql
  src/ol_dbt/models/staging/mitxonline/stg__mitxonline__openedx__mysql__grades_subsectiongradeoverride.sql
  src/ol_dbt/models/staging/mitxpro/_stg_mitxpro__models.yml
  src/ol_dbt/models/staging/mitxpro/stg__mitxpro__openedx__mysql__courseware_studentmodule.sql
Labels: needs review

#1043 add a edx program enrollment int table
  src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
  src/ol_dbt/models/intermediate/edxorg/int__edxorg__mitx_program_enrollments.sql
Labels: product:data-platform, needs review

#1055 add new combined program enrollment mart
  src/ol_dbt/models/marts/combined/_marts__combined__models.yml
  src/ol_dbt/models/marts/combined/marts__combined_program_enrollment_detail.sql
Labels: product:data-platform, needs review

#1056 add a new staging program enrollment table
  src/ol_dbt/models/staging/micromasters/_micromasters__sources.yml
  src/ol_dbt/models/staging/micromasters/_stg_micromasters__models.yml
  src/ol_dbt/models/staging/micromasters/stg__micromasters__app__postgres__dashboard_programenrollment.sql
Labels: product:data-platform, needs review

#1057 add course readable id to combined enrollment mart and upstream models
  src/ol_dbt/models/intermediate/edxorg/_int_edxorg__models.yml
  src/ol_dbt/models/intermediate/edxorg/int__edxorg__mitx_courseruns.sql
  src/ol_dbt/models/intermediate/mitx/_int_mitx__models.yml
  src/ol_dbt/models/intermediate/mitx/int__mitx__courses.sql
  src/ol_dbt/models/marts/combined/_marts__combined__models.yml
  src/ol_dbt/models/marts/combined/marts__combined_course_enrollment_detail.sql
  src/ol_dbt/models/staging/edxorg/_stg__edxorg__models.yml
  src/ol_dbt/models/staging/edxorg/stg__edxorg__bigquery__mitx_courserun.sql
Labels: needs review
